minimum_pre_commit_version: "3.0.4"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
      - id: ruff-format
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v5.0.0"
    hooks:
      - id: end-of-file-fixer
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
      - id: trailing-whitespace
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
      - id: check-json
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
      - id: check-toml
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
      - id: check-yaml
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
  - repo: https://github.com/PyCQA/pylint
    rev: "v3.3.3"
    hooks:
      - id: pylint
        args:
          - --ignore=custom_components/aliexpress_openplatform/iop
          - --disable=import-error,too-few-public-methods
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v1.14.1"
    hooks:
      - id: "mypy"
        name: "Check type hints (mypy)"
        args: [--ignore-missing-imports]
        verbose: true
        exclude: ^(node_modules/|custom_components/aliexpress_openplatform/iop/)
